import {
  CHART_AXIS_SETTINGS_INPUT_CONFIGS_MAP,
  CHART_TRACE_SETTINGS_INPUT_CONFIGS_MAP,
  CHART_TYPES,
  DEFAULT_CHART_AXIS_SETTINGS_INPUT_CONFIG,
  DEFAULT_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
  DEFAULT_CHART_SETTINGS,
  DEFAULT_CHART_SETTINGS_MAP,
  DEFAULT_CHART_TRACE_SETTINGS_INPUT_CONFIG,
  DEFAULT_SERIES_SETTINGS,
  DEFAULT_SERIES_SETTINGS_MAP,
  GENERAL_CHART_SETTINGS_INPUT_CONFIG_MAP,
} from "../constants/charts";

export function getDefaultChartSettings(chartType: string) {
  switch (chartType) {
    case CHART_TYPES.LINE:
      return DEFAULT_CHART_SETTINGS_MAP[CHART_TYPES.LINE];
    case CHART_TYPES.SCATTER:
      return DEFAULT_CHART_SETTINGS_MAP[CHART_TYPES.SCATTER];
    case CHART_TYPES.BAR:
      return DEFAULT_CHART_SETTINGS_MAP[CHART_TYPES.BAR];
    case CHART_TYPES.AREA:
      return DEFAULT_CHART_SETTINGS_MAP[CHART_TYPES.AREA];
    default:
      return DEFAULT_CHART_SETTINGS;
  }
}

export function getDefaultTraceSettings(chartType: string) {
  switch (chartType) {
    case CHART_TYPES.LINE:
      return DEFAULT_SERIES_SETTINGS_MAP[CHART_TYPES.LINE];
    case CHART_TYPES.SCATTER:
      return DEFAULT_SERIES_SETTINGS_MAP[CHART_TYPES.SCATTER];
    case CHART_TYPES.BAR:
      return DEFAULT_SERIES_SETTINGS_MAP[CHART_TYPES.BAR];
    case CHART_TYPES.AREA:
      return DEFAULT_SERIES_SETTINGS_MAP[CHART_TYPES.AREA];
    default:
      return DEFAULT_SERIES_SETTINGS;
  }
}

export function getChartSettingsInputConfig(chartType: string) {
  switch (chartType) {
    case CHART_TYPES.LINE:
      return {
        GENERAL: GENERAL_CHART_SETTINGS_INPUT_CONFIG_MAP[CHART_TYPES.LINE],
        AXIS: CHART_AXIS_SETTINGS_INPUT_CONFIGS_MAP[CHART_TYPES.LINE],
        TRACE: CHART_TRACE_SETTINGS_INPUT_CONFIGS_MAP[CHART_TYPES.LINE],
      };
    case CHART_TYPES.SCATTER:
      return {
        GENERAL: GENERAL_CHART_SETTINGS_INPUT_CONFIG_MAP[CHART_TYPES.SCATTER],
        AXIS: CHART_AXIS_SETTINGS_INPUT_CONFIGS_MAP[CHART_TYPES.SCATTER],
        TRACE: CHART_TRACE_SETTINGS_INPUT_CONFIGS_MAP[CHART_TYPES.SCATTER],
      };
    case CHART_TYPES.BAR:
      return {
        GENERAL: GENERAL_CHART_SETTINGS_INPUT_CONFIG_MAP[CHART_TYPES.BAR],
        AXIS: CHART_AXIS_SETTINGS_INPUT_CONFIGS_MAP[CHART_TYPES.BAR],
        TRACE: CHART_TRACE_SETTINGS_INPUT_CONFIGS_MAP[CHART_TYPES.BAR],
      };
    case CHART_TYPES.AREA:
      return {
        GENERAL: GENERAL_CHART_SETTINGS_INPUT_CONFIG_MAP[CHART_TYPES.AREA],
        AXIS: CHART_AXIS_SETTINGS_INPUT_CONFIGS_MAP[CHART_TYPES.AREA],
        TRACE: CHART_TRACE_SETTINGS_INPUT_CONFIGS_MAP[CHART_TYPES.AREA],
      };
    default:
      return {
        GENERAL: DEFAULT_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
        AXIS: DEFAULT_CHART_AXIS_SETTINGS_INPUT_CONFIG,
        TRACE: DEFAULT_CHART_TRACE_SETTINGS_INPUT_CONFIG,
      };
  }
}
