import {
  AreaChartConfig,
  AreaTraceSettings,
  BarChartConfig,
  BarTraceSettings,
  BaseTraceConfig,
  ScatterChartConfig,
  ScatterTraceSettings,
  TimeChartConfig,
  TimeTraceSettings,
} from "@/modules/playground/types";
import {
  DEFAULT_CHART_AXIS_SETTINGS_INPUT_CONFIG,
  DEFAULT_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
  DEFAULT_CHART_TRACE_SETTINGS_INPUT_CONFIG,
  DEFAULT_CHART_SETTINGS,
  DEFAULT_SERIES_SETTINGS,
} from "./base";
import {
  DEFAULT_TIME_CHART_AXIS_SETTINGS_INPUT_CONFIG,
  DEFAULT_TIME_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
  DEFAULT_TIME_CHART_SETTINGS,
  DEFAULT_TIME_CHART_TRACE_SETTINGS,
  DEFAULT_TIME_CHART_TRACE_SETTINGS_INPUT_CONFIG,
} from "./time";
import {
  DEFAULT_SCATTER_CHART_AXIS_SETTINGS_INPUT_CONFIG,
  DEFAULT_SCATTER_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
  DEFAULT_SCATTER_CHART_SETTINGS,
  DEFAULT_SCATTER_CHART_TRACE_SETTINGS,
  DEFAULT_SCATTER_CHART_TRACE_SETTINGS_INPUT_CONFIG,
} from "./scatter";
import {
  DEFAULT_BAR_CHART_AXIS_SETTINGS_INPUT_CONFIG,
  DEFAULT_BAR_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
  DEFAULT_BAR_CHART_SETTINGS,
  DEFAULT_BAR_CHART_TRACE_SETTINGS,
  DEFAULT_BAR_CHART_TRACE_SETTINGS_INPUT_CONFIG,
} from "./bar";
import {
  DEFAULT_AREA_CHART_AXIS_SETTINGS_INPUT_CONFIG,
  DEFAULT_AREA_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
  DEFAULT_AREA_CHART_SETTINGS,
  DEFAULT_AREA_CHART_TRACE_SETTINGS,
  DEFAULT_AREA_CHART_TRACE_SETTINGS_INPUT_CONFIG,
} from "./area";
import { CHART_TYPES } from "../types";

export * from "./base";
export * from "./time";
export * from "./scatter";
export * from "./bar";
export * from "./area";

export const DEFAULT_CHART_SETTINGS_MAP = {
  [CHART_TYPES.LINE]: { ...DEFAULT_CHART_SETTINGS, ...DEFAULT_TIME_CHART_SETTINGS } as TimeChartConfig["chartSettings"],
  [CHART_TYPES.SCATTER]: {
    ...DEFAULT_CHART_SETTINGS,
    ...DEFAULT_SCATTER_CHART_SETTINGS,
  } as ScatterChartConfig["chartSettings"],
  [CHART_TYPES.BAR]: { ...DEFAULT_CHART_SETTINGS, ...DEFAULT_BAR_CHART_SETTINGS } as BarChartConfig["chartSettings"],
  [CHART_TYPES.AREA]: { ...DEFAULT_CHART_SETTINGS, ...DEFAULT_AREA_CHART_SETTINGS } as AreaChartConfig["chartSettings"],
};

export const DEFAULT_SERIES_SETTINGS_MAP = {
  [CHART_TYPES.LINE]: {
    ...DEFAULT_SERIES_SETTINGS,
    ...DEFAULT_TIME_CHART_TRACE_SETTINGS,
  } as Omit<BaseTraceConfig<TimeTraceSettings>["settings"], "name">,
  [CHART_TYPES.SCATTER]: {
    ...DEFAULT_SERIES_SETTINGS,
    ...DEFAULT_SCATTER_CHART_TRACE_SETTINGS,
  } as Omit<BaseTraceConfig<ScatterTraceSettings>["settings"], "name">,
  [CHART_TYPES.BAR]: {
    ...DEFAULT_SERIES_SETTINGS,
    ...DEFAULT_BAR_CHART_TRACE_SETTINGS,
  } as Omit<BaseTraceConfig<BarTraceSettings>["settings"], "name">,
  [CHART_TYPES.AREA]: {
    ...DEFAULT_SERIES_SETTINGS,
    ...DEFAULT_AREA_CHART_TRACE_SETTINGS,
  } as Omit<BaseTraceConfig<AreaTraceSettings>["settings"], "name">,
};

export const GENERAL_CHART_SETTINGS_INPUT_CONFIG_MAP = {
  [CHART_TYPES.LINE]: [
    ...DEFAULT_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
    ...DEFAULT_TIME_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
  ],
  [CHART_TYPES.SCATTER]: [
    ...DEFAULT_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
    ...DEFAULT_SCATTER_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
  ],
  [CHART_TYPES.BAR]: [
    ...DEFAULT_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
    ...DEFAULT_BAR_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
  ],
  [CHART_TYPES.AREA]: [
    ...DEFAULT_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
    ...DEFAULT_AREA_CHART_GENERAL_SETTINGS_INPUT_CONFIG,
  ],
};

export const CHART_AXIS_SETTINGS_INPUT_CONFIGS_MAP = {
  [CHART_TYPES.LINE]: {
    x: [...DEFAULT_TIME_CHART_AXIS_SETTINGS_INPUT_CONFIG.x, ...DEFAULT_CHART_AXIS_SETTINGS_INPUT_CONFIG.x],
    y: [...DEFAULT_TIME_CHART_AXIS_SETTINGS_INPUT_CONFIG.y, ...DEFAULT_CHART_AXIS_SETTINGS_INPUT_CONFIG.y],
  },
  [CHART_TYPES.SCATTER]: {
    x: [...DEFAULT_SCATTER_CHART_AXIS_SETTINGS_INPUT_CONFIG.x, ...DEFAULT_CHART_AXIS_SETTINGS_INPUT_CONFIG.x],
    y: [...DEFAULT_SCATTER_CHART_AXIS_SETTINGS_INPUT_CONFIG.y, ...DEFAULT_CHART_AXIS_SETTINGS_INPUT_CONFIG.y],
  },
  [CHART_TYPES.BAR]: {
    x: [...DEFAULT_BAR_CHART_AXIS_SETTINGS_INPUT_CONFIG.x, ...DEFAULT_CHART_AXIS_SETTINGS_INPUT_CONFIG.x],
    y: [...DEFAULT_BAR_CHART_AXIS_SETTINGS_INPUT_CONFIG.y, ...DEFAULT_CHART_AXIS_SETTINGS_INPUT_CONFIG.y],
  },
  [CHART_TYPES.AREA]: {
    x: [...DEFAULT_AREA_CHART_AXIS_SETTINGS_INPUT_CONFIG.x, ...DEFAULT_CHART_AXIS_SETTINGS_INPUT_CONFIG.x],
    y: [...DEFAULT_AREA_CHART_AXIS_SETTINGS_INPUT_CONFIG.y, ...DEFAULT_CHART_AXIS_SETTINGS_INPUT_CONFIG.y],
  },
};

export const CHART_TRACE_SETTINGS_INPUT_CONFIGS_MAP = {
  [CHART_TYPES.LINE]: [...DEFAULT_CHART_TRACE_SETTINGS_INPUT_CONFIG, ...DEFAULT_TIME_CHART_TRACE_SETTINGS_INPUT_CONFIG],
  [CHART_TYPES.SCATTER]: [
    ...DEFAULT_CHART_TRACE_SETTINGS_INPUT_CONFIG,
    ...DEFAULT_SCATTER_CHART_TRACE_SETTINGS_INPUT_CONFIG,
  ],
  [CHART_TYPES.BAR]: [...DEFAULT_CHART_TRACE_SETTINGS_INPUT_CONFIG, ...DEFAULT_BAR_CHART_TRACE_SETTINGS_INPUT_CONFIG],
  [CHART_TYPES.AREA]: [...DEFAULT_CHART_TRACE_SETTINGS_INPUT_CONFIG, ...DEFAULT_AREA_CHART_TRACE_SETTINGS_INPUT_CONFIG],
};
